<div class="checkout-debug">
    <div class="checkout-debug__container">
        <div class="checkout-debug__title">Active states</div>
        <div class="checkout-debug__actions">
            <button class="button button--small button--primary" data-body-class="checkout--step-basket">1.Step - Basket</button>
            <button class="button button--small button--primary" data-body-class="checkout--step-delivery">2.Step - Delivery</button>
            <button class="button button--small button--primary" data-body-class="checkout--step-payment">3.Step - Payment</button>
            <button class="button button--small button--primary" data-body-class="checkout--error">Error during checkout</button>
            <button class="button button--small button--primary" data-body-class="checkout--complete">Complete</button>
        </div>
    </div>
</div>