<div class="grid-styleguide">

    <div class="grid-styleguide__box">
        <div class="grid-styleguide__box-title">Buttons</div>
        <div class="grid-styleguide__box-content">

            <div class="grid-styleguide__box-subtitle">Button primary</div>
            <div class="grid-styleguide__box-code">
                <pre><code>.button .button--primary</code> or <code>.button .button--green</code></pre>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--primary">Button primary</button>
                <button class="button button--green">Button green</button>
                <button class="button button--primary button--arrow-right">Button primary arrow right</button>
                <button class="button button--primary" disabled="disabled">Button primary disabled</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--primary button--large">Button primary large</button>
                <button class="button button--primary button--large button--arrow-right">Button primary large arrow right</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--primary button--small">Button primary small</button>
                <button class="button button--primary button--small button--arrow-right">Button primary small arrow right</button>
            </div>

            <div class="grid-styleguide__box-subtitle">Button secondary</div>
            <div class="grid-styleguide__box-code">
                <pre><code>.button .button--secondary</code> or <code>.button .button--blue</code></pre>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--secondary">Button secondary</button>
                <button class="button button--blue">Button blue</button>
                <button class="button button--secondary button--arrow-right">Button secondary arrow right</button>
                <button class="button button--secondary" disabled="disabled">Button secondary disabled</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--secondary button--large">Button secondary large</button>
                <button class="button button--secondary button--large button--arrow-right">Button secondary large arrow right</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--secondary button--small">Button secondary large</button>
                <button class="button button--secondary button--small button--arrow-right">Button secondary small arrow right</button>
            </div>

            <div class="grid-styleguide__box-subtitle">Button third</div>

            <div class="grid-styleguide__box-code">
                <pre><code>.button .button--third</code> or <code>.button .button--red</code></pre>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--third">Button secondary</button>
                <button class="button button--red">Button blue</button>
                <button class="button button--third button--arrow-right">Button secondary arrow right</button>
                <button class="button button--third" disabled="disabled">Button secondary disabled</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--third button--large">Button secondary large</button>
                <button class="button button--third button--large button--arrow-right">Button secondary large arrow right</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--third button--small">Button secondary large</button>
                <button class="button button--third button--small button--arrow-right">Button secondary small arrow right</button>
            </div>

            <div class="grid-styleguide__box-subtitle">Button fifth</div>

            <div class="grid-styleguide__box-code">
                <pre><code>.button .button--fifth</code> or <code>.button .button--gray</code></pre>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--fifth">Button secondary</button>
                <button class="button button--gray">Button blue</button>
                <button class="button button--fifth button--arrow-right">Button secondary arrow right</button>
                <button class="button button--fifth" disabled="disabled">Button secondary disabled</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--fifth button--large">Button secondary large</button>
                <button class="button button--fifth button--large button--arrow-right">Button secondary large arrow right</button>
            </div>
            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--fifth button--small">Button secondary large</button>
                <button class="button button--fifth button--small button--arrow-right">Button secondary small arrow right</button>
            </div>

            <div class="grid-styleguide__box-subtitle">Additional</div>

            <button class="button button--primary button--arrow-left">Button primary arrow left</button>
            <button class="button button--primary button--loading">Button primary loading</button>

            <button class="button button--primary button--pay-by-card">
                <div class="button button--arrow-right">Pay by card</div>
                <div class="payments">
                    <div class="button--payment-mastercard"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em></span></div>
                    <div class="button--payment-visa"><span><em></em></span></div>
                    <div class="button--payment-amex"><span><em></em></span></div>
                </div>
            </button>



            <div class="grid-styleguide__box-subtitle">Button icons</div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--icon button--icon-plus"></button>
                <button class="button button--icon button--icon-minus"></button>
                <button class="button--icon-close"></button>
            </div>

            <div class="grid-styleguide__box-subtitle">Payment icons</div>

            <div class="grid-styleguide__box-code">
                <pre><code>.button .button--payment .button--payment-paypal|amazon|amex|visa|mastercard</code></pre>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">

                <button class="button button--payment button--payment-paypal"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em><em class="path5"></em><em class="path6"></em><em class="path7"></em><em class="path8"></em><em class="path9"></em><em class="path10"></em></span></button>
                <button class="button button--payment button--payment-amazon"><span><em class="path1"></em><em class="path2"></em></span></button>
                <button class="button button--payment button--payment-amex"><span><em></em></span></button>
                <button class="button button--payment button--payment-visa"><span><em></em></span></button>
                <button class="button button--payment button--payment-mastercard"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em></span></button>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--large button--payment button--payment-paypal"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em><em class="path5"></em><em class="path6"></em><em class="path7"></em><em class="path8"></em><em class="path9"></em><em class="path10"></em></span></button>
                <button class="button button--large button--payment button--payment-amazon"><span><em class="path1"></em><em class="path2"></em></span></button>
                <button class="button button--large button--payment button--payment-amex"><span><em></em></span></button>
                <button class="button button--large button--payment button--payment-visa"><span><em></em></span></button>
                <button class="button button--large button--payment button--payment-mastercard"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em></span></button>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--buttons">
                <button class="button button--small button--payment button--payment-paypal"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em><em class="path5"></em><em class="path6"></em><em class="path7"></em><em class="path8"></em><em class="path9"></em><em class="path10"></em></span></button>
                <button class="button button--small button--payment button--payment-amazon"><span><em class="path1"></em><em class="path2"></em></span></button>
                <button class="button button--small button--payment button--payment-amex"><span><em></em></span></button>
                <button class="button button--small button--payment button--payment-visa"><span><em></em></span></button>
                <button class="button button--small button--payment button--payment-mastercard"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em></span></button>
            </div>

        </div>
    </div>

    <div class="grid-styleguide__box">
        <div class="grid-styleguide__box-title">Form elements</div>
        <div class="grid-styleguide__box-content">

            <div class="grid-styleguide__box-subtitle">Input field variations</div>

            <div class="grid-styleguide__row grid-styleguide__row--form">

                <form class="form form--primary">
                    <fieldset>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Double line');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control form__control--nomargin full">
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control full form__control--validated">
                            <label class="form__label"><?php echo $this->__('Label validated');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                            <div class="form__note">Form field note</div>
                        </div>
                        <div class="form__control full form__control--error">
                            <label class="form__label"><?php echo $this->__('Label error');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                            <div class="form__error">This field is required</div>
                        </div>
                        <div class="form__control full form__control--disabled">
                            <label class="form__label"><?php echo $this->__('Label disabled');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" disabled="disabled" />
                            </div>
                        </div>

                        <div class="form__control form__control--autocomplete full">
                            <label class="form__label"><?php echo $this->__('Delivery address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                            <div class="form__autocomplete active">
                                <ul class="form__autocomplete-list">
                                    <li class="form__autocomplete-item">LS1 Headrow, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Palm Assets Ltd, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Pulse, 113 <em>The Headrow</em>, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Retails Express, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Vortex Commerce, 113 The Headrow, Leeds, LS1 5JW</li>
                                </ul>
                            </div>

                            <div class="form__autocomplete-result">
                                <a href="" class="form__autocomplete-edit">Change</a>

                                Vortex Commerce,<br/>
                                LS1 Headrow<br/>
                                113 The Headrow<br/>
                                Leeds<br/>
                                LS1 5JW

                            </div>

                        </div>


                        <div class="form__control form__control--autocomplete full complete">
                            <label class="form__label"><?php echo $this->__('Delivery address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                            <div class="form__autocomplete">
                                <ul class="form__autocomplete-list">
                                    <li class="form__autocomplete-item">LS1 Headrow, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Palm Assets Ltd, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Pulse, 113 <em>The Headrow</em>, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Retails Express, 113 The Headrow, Leeds, LS1 5JW</li>
                                    <li class="form__autocomplete-item">Vortex Commerce, 113 The Headrow, Leeds, LS1 5JW</li>
                                </ul>
                            </div>

                            <div class="form__autocomplete-result">
                                <a href="" class="form__autocomplete-edit">Change</a>

                                Vortex Commerce,<br/>
                                LS1 Headrow<br/>
                                113 The Headrow<br/>
                                Leeds<br/>
                                LS1 5JW

                            </div>

                        </div>

                        <div class="grid-styleguide__box-subtitle">Grid 3 columns 1 - 1 - 1</div>

                        <div class="form__control col-1-3">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-3">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="form__control col-1-3">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="grid-styleguide__box-subtitle">Grid 3 columns 1 - 2</div>

                        <div class="form__control col-1-3">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="form__control col-2-3">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="grid-styleguide__box-subtitle">Grid 4 columns 1 - 1 - 1 -1</div>

                        <div class="form__control col-1-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="grid-styleguide__box-subtitle">Grid 4 columns 2 - 2</div>

                        <div class="form__control col-2-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-2-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>

                        <div class="grid-styleguide__box-subtitle">Grid 4 columns 1 - 3</div>

                        <div class="form__control col-1-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-3-4">
                            <label class="form__label"><?php echo $this->__('Label');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>


                        <div class="form__control form__control--actions">
                            <button class="button button--primary button--arrow-right"><span><?php echo $this->__('Button');?></span></button>
                        </div>
                    </fieldset>
                </form>

            </div>

            <div class="grid-styleguide__box-subtitle">Radio / Checkbox button</div>

            <div class="grid-styleguide__row grid-styleguide__row--radio">
                <form class="form form--primary">
                    <fieldset>
                        <div class="form__radio">
                            <label class="form__label">
                                <input type="radio" name="delivery" class="" value="" />
                                <span class="form__label-text"><?php echo $this->__('Radio - Option 2');?></span>
                            </label>
                        </div>
                        <div class="form__radio">
                            <label class="form__label">
                                <input type="radio" name="delivery" class="" value="" />
                                <span class="form__label-text"><?php echo $this->__('Radio - Option 1');?></span>
                            </label>
                        </div>
                    </fieldset>
                </form>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--radio">
                <form class="form form--primary">
                    <fieldset>
                        <div class="form__checkbox">
                            <label class="form__label">
                                <input type="checkbox" name="address" class="" value="" />
                                <span class="form__label-text"><?php echo $this->__('Checkbox');?></span>
                            </label>
                        </div>
                    </fieldset>
                </form>
            </div>

            <div class="grid-styleguide__box-subtitle">Radio with map</div>

            <div class="grid-styleguide__row grid-styleguide__row--radio">

                <form class="form form--primary">
                    <fieldset>
                        <div class="form__radio form__radio--address">
                            <label class="form__label">
                                <input type="radio" name="delivery" class="" value="" />
                                <div class="form__label-text">
                                    <span class="strong">Peacocks Leeds (Merrion)</span><br/>
                                    0.1 miles <span class="hightlight">NEAREST</span><br/>
                                    16/18 Merrion Centre, LS2 8NG<br/>
                                </div>
                            </label>
                            <div class="cc-map">
                                <a href="" class="cc-map__trigger">
                                    View Details
                                </a>
                                <div class="cc-map__content">
                                    <div class="cc-map__gmap">
                                        <img src="http://via.placeholder.com/660x400" alt="" />
                                    </div>
                                    <dl class="cc-map__timetable">
                                        <dt>Monday</dt>
                                        <dd>9:00–5:30</dd>
                                        <dt>Tuesday</dt>
                                        <dd>9:00–5:30</dd>
                                        <dt>Wednesday</dt>
                                        <dd>9:00–5:30</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                        <div class="form__radio form__radio--address">
                            <label class="form__label">
                                <input type="radio" name="delivery" class="" value="" />
                                <div class="form__label-text">
                                    <span class="strong">Peacocks Leeds (Merrion)</span><br/>
                                    0.1 miles <span class="hightlight">NEAREST</span><br/>
                                    16/18 Merrion Centre, LS2 8NG
                                </div>
                            </label>
                            <div class="cc-map active">
                                <a href="" class="cc-map__trigger active">
                                    Hide Details
                                </a>
                                <div class="cc-map__content">
                                    <div class="cc-map__gmap">
                                        <img src="http://via.placeholder.com/660x400" alt="" />
                                    </div>
                                    <dl class="cc-map__timetable">
                                        <dt>Monday</dt>
                                        <dd>9:00–5:30</dd>
                                        <dt>Tuesday</dt>
                                        <dd>9:00–5:30</dd>
                                        <dt>Wednesday</dt>
                                        <dd>9:00–5:30</dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </form>

            </div>

        </div>
    </div>

    <div class="grid-styleguide__box">
        <div class="grid-styleguide__box-title">Messages</div>
        <div class="grid-styleguide__box-content" style="background:#eee;">

            <div class="grid-styleguide__row grid-styleguide__row--message">
                <div class="checkout-basket__message checkout-basket__message--success">
                    <div class="checkout-basket__message-container">
                        <p>Quantity changed. This is a success message. Sagittis dis mattis parturient vestibulum.</p>
                    </div>
                </div>
            </div>

            <div class="grid-styleguide__row grid-styleguide__row--message">
                <div class="checkout-basket__message checkout-basket__message--error">
                    <div class="checkout-basket__message-container">
                        <p>Quantity changed. This is a success message. Sagittis dis mattis parturient vestibulum.</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="grid-styleguide__box">
        <div class="grid-styleguide__box-title">Loaders</div>
        <div class="grid-styleguide__box-content">

            <div class="grid-styleguide__box-subtitle">Local loader</div>

            <div class="grid-styleguide__box-code">
                <pre><code>.checkout-loader .active</code></pre>
            </div>

            <div class="grid-styleguide__loader-content">
                Loader content
                <div class="checkout-loader active"><div class="checkout-loader__spinner"><span></span></div></div>
            </div>


            <div class="grid-styleguide__box-subtitle">Global loader </div>

            <div class="grid-styleguide__box-code">
                <pre><code>.checkout-loader .checkout-loader--large .active</code> or <br/><code>.checkout-loader .checkout-loader--large .checkout-loader--overlay .active</code></pre>
            </div>

            <div class="grid-styleguide__loader-content">
                Loader content
                <div class="checkout-loader checkout-loader--large active"><div class="checkout-loader__spinner"><span></span></div></div>
            </div>

        </div>
    </div>

    <div class="grid-styleguide__box">
        <div class="grid-styleguide__box-title">Modal window</div>
        <div class="grid-styleguide__box-content">

            <div class="grid-styleguide__box-code">
                <pre><code>.checkout-modal .loading|.active</code></pre>
            </div>

            <button class="button button--primary" onClick="{document.getElementById('checkout-modal-1').className=document.getElementById('checkout-modal-1').className + ' active';}"><span>Open modal window</span></button>

            <div class="checkout-modal" id="checkout-modal-1">
                <div class="checkout-loader checkout-loader--large checkout-loader--dark checkout-loader--overlay"><div class="checkout-loader__spinner"><span></span></div></div>
                <div class="checkout-modal__container">
                    <a class="checkout-modal__close button--icon-close" onClick="{document.getElementById('checkout-modal-1').className=document.getElementById('checkout-modal-1').className.replace(' active', '');}"></a>

                    <div class="checkout-modal__title">Edit delivery address</div>

                    <div class="form form--modal">
                        <div class="form__control col-2-4">
                            <label class="form__label"><?php echo $this->__('Last name');?></label>
                            <div class="form__input">
                                <input type="text" class="" value=""/>
                            </div>
                        </div>
                        <div class="form__control col-2-4">
                            <label class="form__label"><?php echo $this->__('Last name');?></label>
                            <div class="form__input">
                                <input type="text" class="" value=""/>
                            </div>
                        </div>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Phone');?></label>
                            <div class="form__input">
                                <input type="phone" class="" value=""/>
                            </div>
                        </div>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Address line');?></label>
                            <div class="form__input">
                                <input type="text" class="" value=""/>
                            </div>
                            <div class="form__input">
                                <input type="text" class="" value=""/>
                            </div>
                        </div>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Country');?></label>
                            <div class="form__input">
                                <select>
                                    <option>United Kingdom</option>
                                    <option>Brazil</option>
                                    <option>Usa</option>
                                </select>
                            </div>
                        </div>
                        <div class="form__control form__control--actions">
                            <button class="button button--small button--fifth" onClick="{document.getElementById('checkout-modal-1').className=document.getElementById('checkout-modal-1').className.replace(' active', '');}"><span><?php echo $this->__('Delete');?></span></button>
                            <button class="button button--small button--fifth" onClick="{document.getElementById('checkout-modal-1').className=document.getElementById('checkout-modal-1').className.replace(' active', '');}"><span><?php echo $this->__('Cancel');?></span></button>
                            <button class="button button--secondary" onClick="{document.getElementById('checkout-modal-1').className=document.getElementById('checkout-modal-1').className.replace(' active', '');}"><span><?php echo $this->__('Save this address');?></span></button>
                        </div>
                    </div>

                </div>
            </div>


        </div>
    </div>

</div>