export const STATE_BASKET = 'STATE_BASKET';
export const STATE_EMAIL = 'STATE_EMAIL';
export const STATE_PASSWORD = 'STATE_PASSWORD';
export const STATE_DELIVERY = 'STATE_DELIVERY';
export const STATE_PAYMENT = 'STATE_PAYMENT';
export const STATE_BILLING_ADDRESS = 'STATE_BILLING_ADDRESS';
export const STATE_SUCCESS = 'STATE_SUCCESS';

export const steps = [
    STATE_BASKET,
    STATE_EMAIL,
    STATE_PASSWORD,
    STATE_DELIVERY,
    STATE_PAYMENT,
    STATE_BILLING_ADDRESS,
    STATE_SUCCESS
];