export const LOAD_BASKET_SUCCESS = 'LOAD_BASKET_SUCCESS';

export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';

export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const REMOVE_DELIVERY_METHODS = 'REMOVE_DELIVERY_METHODS';

export const ADD_GLOBAL_ERROR = 'ADD_GLOBAL_ERROR';
export const ADD_BASKET_ERROR = 'ADD_BASKET_ERROR';
export const ADD_PAYMENT_ERROR = 'ADD_PAYMENT_ERROR';
export const CLEAR_ALL_ERRORS = 'CLEAR_ALL_ERRORS';

export const CHANGE_CHECKOUT_SECTION = 'CHANGE_CHECKOUT_SECTION';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';