<?php
/**
 * @var Mage_Core_Block_Template $this
 */
?>


<div class="checkout-section checkout-section--basket">
    <div class="checkout-section__title">
        <div class="checkout-section__title-text">
            <?php echo $this->__('<span class="checkout-section__title-count">2</span> items in your bag'); ?>
        </div>
        <div class="checkout-section__title-actions">
            <button class="button button--small button--primary"><?php echo $this->__('Checkout')?></button>
        </div>
        <a href="" class="checkout-section__title-link"><?php echo $this->__('<span class="checkout-section__title-count">2</span> items in your bag'); ?></a>
    </div>
    <div class="checkout-section__container">

        <div class="checkout-basket__items">
            <div class="checkout-basket__item">
                <div class="checkout-basket__img">
                    <img src="http://via.placeholder.com/120x160" alt=""/>
                </div>

                <div class="checkout-basket__item-info">

                    <div class="checkout-basket__item-title">
                        <a href="">Womens Black Across Body Bag</a>
                    </div>
                    <div class="checkout-basket__item-price">
                        <div clas="checkout-basket__price-box">
                            <span class="regular-price">
                                <span clas="label"><?php $this->__('Regular price')?></span>
                                <span class="price">&pound;12</span>
                            </span>
                        </div>
                    </div>
                    <ul class="checkout-basket__item-details">
                        <li class="checkout-basket__item-detail">
                            <span class="checkout-basket__item-detail-label">Size: 4</span>
                            <a href="" class="checkout-basket__item-link"><?php echo $this->__('Change');?></a>
                        </li>
                    </ul>
                    <div class="checkout-basket__qty">
                        <div class="checkout-basket__qty-button">
                            <button class="button button--icon button--minus"></button>
                        </div>
                        <input type="text" class="input" />
                        <div class="checkout-basket__qty-button">
                            <button class="button button--icon button--plus"></button>
                        </div>
                    </div>

                </div>

                <button class="checkout-basket__item-remove button--icon button--close"></button>

            </div>

            <div class="checkout-basket__item">
                <div class="checkout-basket__img">
                    <img src="http://via.placeholder.com/120x160" alt=""/>
                </div>

                <div class="checkout-basket__item-info">

                    <div class="checkout-basket__item-title">
                        <a href="">Womens Black Across Body Bag</a>
                    </div>
                    <div class="checkout-basket__item-price">
                        <div clas="checkout-basket__price-box">
                            <span class="old-price">
                                <span clas="label"><?php $this->__('Old price')?></span>
                                <span class="price">&pound;20</span>
                            </span>
                            <span class="special-price">
                                <span clas="label"><?php $this->__('Special price')?></span>
                                <span class="price">&pound;15</span>
                            </span>
                        </div>
                    </div>
                    <ul class="checkout-basket__item-details">
                        <li class="checkout-basket__item-detail">
                            <span class="checkout-basket__item-detail-label">Size: 4</span>
                            <a href="" class="checkout-basket__item-link"><?php echo $this->__('Change');?></a>
                        </li>
                    </ul>
                    <div class="checkout-basket__qty">
                        <div class="checkout-basket__qty-button">
                            <button class="button button--icon button--minus"></button>
                        </div>
                        <input type="text" class="input" />
                        <div class="checkout-basket__qty-button">
                            <button class="button button--icon button--plus"></button>
                        </div>
                    </div>

                </div>

                <button class="checkout-basket__item-remove button--icon button--close"></button>

            </div>

        </div>

        <div class="checkout-basket__totals">
            <div class="checkout-basket__total">
                <div class="checkout-basket__total-label">Sub total</div>
                <div class="checkout-basket__total-price">&pound;27</div>
            </div>
            <div class="checkout-basket__total">
                <div class="checkout-basket__total-label">Delivery</div>
                <div class="checkout-basket__total-price">&pound;3.99</div>
            </div>
            <div class="checkout-basket__discount">
                <a href=""><?php echo $this->__('Add discount code?')?></a>
                <form class="form form--discount">
                    <fieldset>
                        <label><?php echo $this->__('Add discount code?')?></label>
                        <div class="form__control col-2-3">
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-3 form__control--actions">
                            <button class="button button--secondary button--small"><?php echo $this->__('Add');?></button>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="checkout-basket__total checkout-basket__total--grand">
                <div class="checkout-basket__total-label">Sub total</div>
                <div class="checkout-basket__total-price">&pound;27</div>
            </div>

            <div class="checkout-basket__total-button">
                <button class="button button--primary">
                    <span><?php echo $this->__('Continue to Checkout')?></span>
                </button>
            </div>

        </div>

        <div class="checkout-basket__crosssell">
            <div class="checkout-crosssell">
                <div class="checkout-crosssell__container">
                    Checkout Crossell area
                </div>
            </div>
        </div>

    </div>
</div>
