<?php
/**
 * @var Mage_Core_Block_Template $this
 */
?>


<div class="checkout-section checkout-section--checkout">
    <div class="checkout-section__container">

        <div class="checkout-login">
            <div class="checkout-login__container">
                <form class="form form--primary">
                    <fieldset>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Email address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control full">
                            <label class="form__label"><?php echo $this->__('Email address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control full form__control--validated">
                            <label class="form__label"><?php echo $this->__('Email address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-3 form__control--error">
                            <label class="form__label"><?php echo $this->__('Email address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-2-3 form__control--disabled">
                            <label class="form__label"><?php echo $this->__('Email address');?></label>
                            <div class="form__input">
                                <input type="text" class="" value="" disabled="disabled" />
                            </div>
                        </div>
                        <div class="form__control form__control--actions">
                            <button class="button button--primary button--arrow-right"><span><?php echo $this->__('Continue');?></span></button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>

        <div class="checkout-register">
            <div class="checkout-register__container">

            </div>
        </div>

    </div>
</div>
