<?php
/**
 * @var Mage_Core_Block_Template $this
 */
?>


<div class="checkout-section checkout-section--basket">
    <div class="checkout-section__title">
        <div class="checkout-section__title-text">
            <?php echo $this->__('<span class="checkout-section__title-count">2</span> items in your bag'); ?>
        </div>
        <div class="checkout-section__title-actions">
            <button class="button button--small button--primary"><?php echo $this->__('Checkout')?></button>
        </div>
        <a href="" class="checkout-section__title-link"><?php echo $this->__('<span class="checkout-section__title-count">2</span> items in your bag'); ?></a>
    </div>
    <div class="checkout-section__container">

        <div class="checkout-basket__message checkout-basket__message--success">
            <div class="checkout-basket__message-container">
                <p>Quantity changed. This is a success message. Sagittis dis mattis parturient vestibulum.</p>
            </div>
        </div>

        <div class="checkout-basket__items">
            <div class="checkout-basket__item">
                <div class="checkout-basket__img">
                    <img src="http://via.placeholder.com/120x160" alt=""/>
                </div>

                <div class="checkout-basket__item-info">

                    <div class="checkout-basket__item-title">
                        <a href="">Womens Black Across Body Bag</a>
                    </div>
                    <div class="checkout-basket__item-price">
                        <div class="checkout-basket__price-box">
                            <span class="regular-price">
                                <span class="label"><?php $this->__('Regular price')?></span>
                                <span class="price">&pound;12</span>
                            </span>
                        </div>
                    </div>
                    <ul class="checkout-basket__item-attributes">
                        <li class="checkout-basket__item-attribute">
                            <span class="checkout-basket__item-attribute-label">Size: 4</span>
                            <a href="" class="checkout-basket__item-link"><?php echo $this->__('Change');?></a>
                        </li>
                    </ul>
                    <div class="checkout-basket__qty">
                        <form class="form form--qty">
                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-minus" disabled="disabled"></button>
                            </div>

                            <div class="form__control">
                                <div class="form__input">
                                    <input type="text" min="1" value="1"/>
                                </div>
                            </div>

                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-plus"></button>
                            </div>
                        </form>
                    </div>

                </div>

                <button class="checkout-basket__item-remove button--icon button--icon-close"></button>

            </div>

            <div class="checkout-basket__item">
                <div class="checkout-basket__img">
                    <img src="http://via.placeholder.com/120x160" alt=""/>
                </div>

                <div class="checkout-basket__item-info">

                    <div class="checkout-basket__item-title">
                        <a href="">Womens Black Across Body Bag</a>
                    </div>
                    <div class="checkout-basket__item-price">
                        <div class="checkout-basket__price-box">
                            <span class="old-price">
                                <span class="label"><?php $this->__('Old price')?></span>
                                <span class="price">&pound;20</span>
                            </span>
                            <span class="special-price">
                                <span class="label"><?php $this->__('Special price')?></span>
                                <span class="price">&pound;15</span>
                            </span>
                        </div>
                    </div>
                    <ul class="checkout-basket__item-attributes">
                        <li class="checkout-basket__item-attribute">
                            <span class="checkout-basket__item-attribute-label">Size: 4</span>
                            <a href="" class="checkout-basket__item-link"><?php echo $this->__('Change');?></a>
                        </li>
                    </ul>
                    <div class="checkout-basket__qty">
                        <form class="form form--qty">
                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-minus" disabled="disabled"></button>
                            </div>

                            <div class="form__control">
                                <div class="form__input">
                                    <input type="text" min="1" value="1"/>
                                </div>
                            </div>

                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-plus"></button>
                            </div>
                        </form>
                    </div>

                </div>

                <button class="checkout-basket__item-remove button--icon button--icon-close"></button>

            </div>

            <div class="checkout-basket__item">
                <div class="checkout-basket__img">
                    <img src="http://via.placeholder.com/120x160" alt=""/>
                </div>

                <div class="checkout-basket__item-info">

                    <div class="checkout-basket__item-title">
                        <a href="">Womens Black Across Body Bag</a>
                    </div>
                    <div class="checkout-basket__item-price">
                        <div class="checkout-basket__price-box">
                            <span class="regular-price">
                                <span class="label"><?php $this->__('Regular price')?></span>
                                <span class="price">&pound;12</span>
                            </span>
                        </div>
                    </div>
                    <ul class="checkout-basket__item-attributes">
                        <li class="checkout-basket__item-attribute">
                            <span class="checkout-basket__item-attribute-label">Size: 4</span>
                            <a href="" class="checkout-basket__item-link"><?php echo $this->__('Change');?></a>
                        </li>
                    </ul>
                    <div class="checkout-basket__qty">
                        <form class="form form--qty">
                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-minus"></button>
                            </div>

                            <div class="form__control">
                                <div class="form__input">
                                    <input type="text" min="1" value="1"/>
                                </div>
                            </div>

                            <div class="checkout-basket__qty-button">
                                <button class="button button--icon button--icon-plus"></button>
                            </div>
                        </form>
                    </div>

                </div>

                <button class="checkout-basket__item-remove button--icon button--icon-close"></button>

                <div class="checkout-loader active"><div class="checkout-loader__spinner"><span></span></div></div>

            </div>

            <div class="checkout-loader checkout-loader--large"><div class="checkout-loader__spinner"><span></span></div></div>

        </div>

        <div class="checkout-basket__totals checkout-basket__totals--primary">
            <div class="checkout-basket__total">
                <div class="checkout-basket__total-label">Sub total</div>
                <div class="checkout-basket__total-price">&pound;27</div>
            </div>
            <div class="checkout-basket__total">
                <div class="checkout-basket__total-label">Delivery</div>
                <div class="checkout-basket__total-price">&pound;3.99</div>
            </div>
            <div class="checkout-basket__total checkout-basket__total--extra">
                <div class="checkout-basket__total-label">Multibuy offer</div>
                <div class="checkout-basket__total-price">-&pound;1.00</div>
            </div>
            <div class="checkout-basket__discount">
                <a href=""><?php echo $this->__('Add discount code?')?></a>
                <form class="form form--discount">
                    <fieldset>
                        <label><?php echo $this->__('Add discount code?')?></label>
                        <div class="form__control col-2-3">
                            <div class="form__input">
                                <input type="text" class="" value="" />
                            </div>
                        </div>
                        <div class="form__control col-1-3 form__control--actions">
                            <button class="button button--secondary button--arrow-right"><?php echo $this->__('Add');?></button>
                        </div>
                    </fieldset>
                </form>
            </div>
            <div class="checkout-basket__total checkout-basket__total--grand">
                <div class="checkout-basket__total-label">Total</div>
                <div class="checkout-basket__total-price">&pound;30.99</div>
            </div>

            <div class="checkout-basket__total-action">
                <button class="button button--primary button--arrow-right">
                    <span><?php echo $this->__('Continue to Checkout')?></span>
                </button>
                <div class="checkout-basket__total-action-payments">
                    <button class="button--payment button--small button--payment-paypal"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em><em class="path5"></em><em class="path6"></em><em class="path7"></em><em class="path8"></em><em class="path9"></em><em class="path10"></em></span></button>
                    <button class="button--payment button--small button--payment-amazon"><span><em class="path1"></em><em class="path2"></em></span></button>
                    <button class="button--payment button--payment-mastercard"><span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em></span></button>
                    <button class="button--payment button--small button--payment-visa"><span><em></em></span></button>
                    <button class="button--payment button--payment-amex"><span><em></em></span></button>
                </div>
            </div>

            <div class="checkout-basket__total-express">
                <div class="checkout-basket__total-express-title">Express checkout <small>(delivery only)</small></div>

                <div class="checkout-basket__total-express-buttons">

                    <button class="button button--payment button--payment-paypal">
                        <span><em class="path1"></em><em class="path2"></em><em class="path3"></em><em class="path4"></em><em class="path5"></em><em class="path6"></em><em class="path7"></em><em class="path8"></em><em class="path9"></em><em class="path10"></em></span>
                    </button>
                    <button class="button button--payment button--payment-amazon">
                        <span><em class="path1"></em><em class="path2"></em></span>
                    </button>

                </div>

            </div>

        </div>

        <div class="checkout-basket__crosssell">
            <div class="checkout-crosssell">
                <div class="checkout-crosssell__container">
                    Checkout Crossell area
                </div>
            </div>
        </div>

    </div>

</div>
