<?php
/**
 * @var Mage_Core_Block_Template $this
 */
?>


<div class="checkout-section checkout-section--success-bottom">

    <div class="checkout-section__container">

        <div class="checkout-success__box checkout-success__box--secondary">
            <div class="checkout-success__details">
                <div class="checkout-success__details-title">Billing address</div>
                <p>Bruce Mead <br/>Vortex Commerce <br/>LS1 Headrow, 113 The Headrow<br/> Leeds<br/> LS1 5JW</p>
            </div>
            <div class="checkout-success__details">
                <div class="checkout-success__details-title">Shipping address</div>
                <p>Bruce Mead <br/>Vortex Commerce <br/>LS1 Headrow, 113 The Headrow<br/> Leeds<br/> LS1 5JW</p>
            </div>

            <div class="checkout-success__details">
                <div class="checkout-success__details-title">Payment method</div>
                <p>American Express ending in 1234</p>
            </div>

            <div class="checkout-success__details">
                <div class="checkout-success__details-title">Delivery information</div>
                <p>UK Standard (3–5 working days)</p>
            </div>
        </div>

        <div class="checkout-success__box checkout-success__box--primary">
            <div class="checkout-success__banner">
                <a href="">
                    <img src="http://via.placeholder.com/440x200" alt=""/>
                </a>
            </div>
            <div class="checkout-success__text">
                <p>At tempus a lacinia aliquam netus a ut ultricies consequat id himenaeos diam vestibulum a ac ultrices ullamcorper.
Ullamcorper suspendisse dis felis a parturient dapibus hac eget.</p>
            </div>
        </div>

    </div>

</div>
