<?php
/**
 * @var Mage_Core_Block_Template $this
 */
?>


<div class="checkout-section checkout-section--success-top">

    <div class="checkout-section__title">
        <div class="checkout-section__title-text">
            <?php echo $this->__('Thank you!'); ?>
        </div>
    </div>

    <div class="checkout-section__container">

        <div class="checkout-success">
            <div class="checkout-success__msg">
                <p>Your order has been successfully placed.<br/>Order number: <a href="">1000023405</a></p>
            </div>
        </div>

        <div class="checkout-success__box checkout-success__box--primary">
            <div class="checkout-success__banner">
                <a href="">
                    <img src="http://via.placeholder.com/440x200" alt=""/>
                </a>
            </div>
            <div class="checkout-success__text">
                <p>At tempus a lacinia aliquam netus a ut ultricies consequat id himenaeos diam vestibulum a ac ultrices ullamcorper.
Ullamcorper suspendisse dis felis a parturient dapibus hac eget.</p>
            </div>
        </div>

    </div>

</div>
